### ISSUE TITLE
Suggestion: Data tables are not downloadable or user friendly

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/open-contracting.github.io#6]
Hey!

The data tables in the documentation can not be downloaded. They are not user friendly when doing basic row count, sort or filter. I am assuming those are embeds. Here is a sample table.

![ocp-help-tables](https://cloud.githubusercontent.com/assets/521705/15914031/b0b61f54-2dab-11e6-93dd-8f24e6196903.PNG)

It would be great if you can add filtering/sorting/row counts or just enable a simple file download.

Thanks!

**Comment by timgdavies** [comment]
Moved to https://github.com/open-contracting/standard/issues/340
