### ISSUE TITLE
Add a simple FAQ

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/open-contracting.github.io#7]
It would be of great use if you can publish a simple FAQ with the most popular questions that you get to the help desk.

**Comment by timgdavies** [comment]
We're looking into this - though mostly trying to improve the docs in-line, rather than put together FAQ - as experience so far shows there are few consistent FAQs, and most of the questions we get in require a more customised response. 

(Closing here, but logging in helpdesk development plans)
